name: Update Courtminutes Links

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyairtable

      - name: Run script
        env:
          KEY: ${{ secrets.KEY }}
        run: python update_courtminutes.py
