name: Run Airtable Scraper

on:
 workflow_dispatch:  # manually trigger
  schedule:
    - cron: "45 15 * * 1-5"  # 8:45 AM MST (15:45 UTC), Mon–Fri
    - cron: "45 23 * * 1-5"  # 4:45 PM MST (23:45 UTC), Mon–Fri

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: python link_scraper.py
